### ISSUE TITLE
"In inizio gennaio"

### ISSUE THREAD

**Issue by ljl-covid** [apertium/apertium-srd-ita#1]
In [this commit](https://github.com/apertium/apertium-srd-ita/commit/114e1b6741b27c030c612a1c91b71c47f27f6812), months are apparently paired with the words "inizio" and "fine", and the preposition "in" is left unchanged between Italian and Sardinian.

However, to me, "a inizio gennaio" or "ad inizio gennaio" are idiomatic, while "in inizio gennaio" is not idiomatic at all. I am a native Italian speaker, for what it's worth, but maybe [these Google N-grams](https://books.google.com/ngrams/graph?content=in+inizio+gennaio%2Ca+inizio+gennaio%2Cad+inizio+gennaio&year_start=1800&year_end=2019&corpus=33&smoothing=3#) could help with the subjectiveness of my assessment.

**Comment by hectoralos** [comment]
Yes, you are right, thanks! The problem is not in the rule, but in the example associated to it. I'll change it. The preposition is left unchanged in the rule, whatever it is ("a", "fra", etc.). In fact, I think "a" should be changed to "in", but this would be added to the lexical selection rules associated to preposition "a".
